<header>
    <nav>
        <a href="index.php" id="league">THE LEAGUE</a>
        <ul>
            <li>
                <a href="index.php?route=list_teams">LES TEAMS</a>
            </li>
            <li>
                <a href="index.php?route=list_players">LES PLAYERS</a>
            </li>
            <li>
                <a href="index.php?route=list_matchs">LES MATCHS</a>
            </li>
        </ul>
    </nav>
</header>
