<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>The League</title>
        <link rel="stylesheet" href="assets/css/detail_joueur_team.css" />
        <link rel="stylesheet" href="assets/css/_detail_matchs.css" />
        <link rel="stylesheet" href="assets/css/detail_team.css" />
        <link rel="stylesheet" href="assets/css/player.css" />
        <link rel="stylesheet" href="assets/css/body.css" />
        <link rel="stylesheet" href="assets/css/list_teams.css" />
        <link rel="stylesheet" href="assets/css/header.css" />
        <link rel="stylesheet" href="assets/css/match.css" />
        <link rel="stylesheet" href="assets/css/matchs.css" />
        <link rel="stylesheet" href="assets/css/homepage.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Ubuntu:wght@700&display=swap" rel="stylesheet">
    </head>
    <body>
        <?php require "templates/$template.phtml";?>
    </body>
</html>